version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez
        columns:
          - name: date_date
          - name: orders_id
          - name: products_id
            description: forgan key cor to the products_id
          - name: revenue
          - name: quantity
        tests: 
          - unique:
              column_name: "(orders_id ||'-'|| products_id)"
  
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: primary key of the table
            tests: 
              - unique
              - not_null
          - name: purchase_price
          
      - name: ship
        identifier: raw_gz_ship
        description: ships of greenweez
        columns:
          - name: orders_id
            description: primary key of the table
            tests: 
              - unique
              - not_null
          - name: shipping_fee
          - name: logCost
          - name: ship_cost