version: 2
sources:
  - name: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales 
        identifier: raw_gz_sales 
        description: sales of greenweez
      - name : product
        identifier: raw_gz_product 
        description: product info of greenweez
        columns:
          - name: product_id
            description: primary key of table
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: information about ship of greenweez